version: "3"
services:
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_USERNAME=Abdullah
      - DB_PASSWORD=myPassword
      - DB_NAME=online-warehouse-system
    depends_on:
      - db
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Abdullah
      - MONGO_INITDB_ROOT_PASSWORD=myPassword
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: