version: "3"
services:
  api:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./backend:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development